import { CaptionTemplate } from "./types";

// قوالب ترجمة بأنماط شائعة في السوشال ميديا (نمط Submagic / Hormozi / Beasty...).
export const CAPTION_TEMPLATES: CaptionTemplate[] = [
  {
    id: "hormozi",
    name: "Hormozi",
    fontFamily: "'Arial Black', system-ui, sans-serif",
    fontWeight: 900,
    fontSizeVw: 6.5,
    textColor: "#ffffff",
    activeColor: "#ffe600",
    stroke: "#000000",
    strokeWidth: 8,
    uppercase: true,
    position: "center",
    maxWordsPerLine: 3,
    shadow: "0 4px 12px rgba(0,0,0,0.6)",
    pop: true,
  },
  {
    id: "beasty",
    name: "Beasty",
    fontFamily: "'Arial Black', system-ui, sans-serif",
    fontWeight: 900,
    fontSizeVw: 6,
    textColor: "#ffffff",
    activeColor: "#00e676",
    activeBg: "rgba(0,0,0,0.0)",
    stroke: "#000000",
    strokeWidth: 7,
    uppercase: true,
    position: "bottom",
    maxWordsPerLine: 4,
    shadow: "0 3px 10px rgba(0,0,0,0.7)",
    pop: true,
  },
  {
    id: "highlight",
    name: "Highlight",
    fontFamily: "system-ui, 'Segoe UI', sans-serif",
    fontWeight: 800,
    fontSizeVw: 5.5,
    textColor: "#ffffff",
    activeColor: "#ffffff",
    activeBg: "#7c3aed",
    stroke: "#000000",
    strokeWidth: 4,
    uppercase: false,
    position: "bottom",
    maxWordsPerLine: 5,
    shadow: "0 2px 8px rgba(0,0,0,0.6)",
    pop: false,
  },
  {
    id: "neon",
    name: "Neon",
    fontFamily: "system-ui, 'Segoe UI', sans-serif",
    fontWeight: 800,
    fontSizeVw: 5.5,
    textColor: "#f0f0ff",
    activeColor: "#22d3ee",
    stroke: "#0a0a23",
    strokeWidth: 3,
    uppercase: false,
    position: "bottom",
    maxWordsPerLine: 5,
    shadow: "0 0 14px rgba(34,211,238,0.8)",
    pop: false,
  },
  {
    id: "clean",
    name: "Clean",
    fontFamily: "system-ui, 'Segoe UI', sans-serif",
    fontWeight: 700,
    fontSizeVw: 4.8,
    textColor: "#ffffff",
    activeColor: "#ffd400",
    stroke: "#000000",
    strokeWidth: 2,
    uppercase: false,
    position: "bottom",
    maxWordsPerLine: 6,
    shadow: "0 2px 6px rgba(0,0,0,0.5)",
    pop: false,
  },
];

export function getTemplate(id: string): CaptionTemplate {
  return CAPTION_TEMPLATES.find((t) => t.id === id) ?? CAPTION_TEMPLATES[0];
}
