// @ts-ignore
import pkg from 'whatsapp-web.js';
const { Client, LocalAuth, MessageMedia } = pkg;
// @ts-ignore
import qrcode from 'qrcode-terminal';
import { generateResponse } from './llm/client.js';
import { addMemory, getMemory } from './db/database.js';
import { generateImageDirectly, generateVideoDirectly } from './tools/media.js';
import { config } from './config.js';

console.log("🟠 Initializing WhatsApp Client...");

const client = new Client({
    authStrategy: new LocalAuth({
        clientId: "rashid_final_v1"
    }),
    puppeteer: {
        headless: true,
        args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-dev-shm-usage-log',
            '--disable-gpu'
        ]
    }
});

client.on('qr', (qr) => {
    console.log('📱 SCAN THIS QR CODE WITH YOUR WHATSAPP:');
    qrcode.generate(qr, { small: true });
});

client.on('ready', () => {
    console.log('✅ RashidClaw is READY on WhatsApp!');
});

const SYSTEM_PROMPT = `أنت RashidClaw، وكيل ذكاء اصطناعي عربي متقدم وخبير يعمل الآن عبر واتساب.
مهمتك: فهم أفكار المستخدم وتنفيذها باحترافية والرد بأسلوب طبيعي ومفيد.
عند طلب صورة أو فيديو، ستحصل عليه فوراً في الشات.`;

const IMAGE_KEYWORDS = ['صورة', 'صوره', 'ارسم', 'صمم', 'تصميم', 'ولد', 'أنشئ', 'image', 'draw', 'create', 'design'];
const VIDEO_KEYWORDS = ['فيديو', 'فيلم', 'مقطع', 'متحرك', 'حرك', 'video', 'movie', 'clip', 'animate'];

function isVideoRequest(text: string): boolean {
    const lower = text.toLowerCase();
    return VIDEO_KEYWORDS.some(k => lower.includes(k));
}

function isImageRequest(text: string): boolean {
    const lower = text.toLowerCase();
    if (isVideoRequest(text)) return false;
    return IMAGE_KEYWORDS.some(k => lower.includes(k));
}

client.on('message_create', async (msg) => {
    // تجاهل الرسائل التي يرسلها البوت نفسه للآخرين، لكن اسمح بالرسائل التي يرسلها المستخدم لنفسه للتجربة
    if (msg.fromMe && (msg.to !== msg.from)) return;
    
    // إذا كنت لا تريد أن يرد البوت على كل رسائلك التي ترسلها للآخرين، اترك السطر أعلاه
    
    const contact = await msg.getContact();
    const userIdStr = contact.id.user; 
    
    // تخطي رسائل الحالات (Status)
    if (msg.isStatus) return;
    
    // Whitelist check
    const allowedList = config.ALLOWED_USERS.map(id => id.toString());
    
    if (!allowedList.includes(userIdStr)) {
        return; // إذا لم يكن الرقم مسموحاً به
    }

    const text = msg.body;
    console.log(`\n━━━ WhatsApp from ${contact.pushname || userIdStr}: ${text} ━━━`);

    try {
        // 1. Direct Video Request
        if (isVideoRequest(text)) {
            await msg.reply("🎥 جاري إنتاج فيديو إبداعي خاص بك عبر محرك Grok...\n⏳ هذه العملية تستغرق حوالي دقيقة، يرجى الانتظار!");
            try {
                const buffer = await generateVideoDirectly(text);
                if (buffer) {
                    const media = new MessageMedia('video/mp4', buffer.toString('base64'), 'video.mp4');
                    await client.sendMessage(msg.from, media, { caption: "🎥 المشهد السينمائي جاهز من محرك Grok!" });
                    return;
                }
            } catch (err: any) {
                console.error("Video fail:", err.message);
                await msg.reply(`❌ فشل توليد الفيديو: ${err.message}`);
                return;
            }
        }

        // 2. Direct Image Request
        if (isImageRequest(text)) {
            await msg.reply("⏳ جاري رسم وتوليد صورتك عبر محرك Flow الخارق... انتظر قليلاً!");
            try {
                const buffer = await generateImageDirectly(text);
                if (buffer) {
                    const media = new MessageMedia('image/png', buffer.toString('base64'), 'photo.png');
                    await client.sendMessage(msg.from, media, { caption: "🎨 صورتك الاحترافية جاهزة!" });
                    return;
                }
            } catch (err: any) {
                console.error("Image fail:", err.message);
                await msg.reply(`❌ فشل توليد الصورة حالياً: ${err.message}`);
                return;
            }
        }

        // 3. Normal LLM Response
        await addMemory(userIdStr, 'user', text);
        const history = await getMemory(userIdStr, 10);
        const messages = [{ role: 'system', content: SYSTEM_PROMPT }, ...history];

        const responseText = await generateResponse(messages);
        await addMemory(userIdNum, 'assistant', responseText);

        // Handle Base64 payloads if generated by LLM tools
        if (responseText.includes('__IMAGE_PAYLOAD_BASE64__')) {
            const parts = responseText.split('__IMAGE_PAYLOAD_BASE64__');
            if (parts.length > 1) {
                const base64Str = parts[1].split('\n')[0].trim();
                const media = new MessageMedia('image/png', base64Str, 'photo.png');
                await client.sendMessage(msg.from, media, { caption: "🎨 إليك صورتك!" });
                return;
            }
        } else if (responseText.includes('__VIDEO_PAYLOAD_BASE64__')) {
            const parts = responseText.split('__VIDEO_PAYLOAD_BASE64__');
            if (parts.length > 1) {
                const base64Str = parts[1].split('\n')[0].trim();
                const media = new MessageMedia('video/mp4', base64Str, 'video.mp4');
                await client.sendMessage(msg.from, media, { caption: "🎥 تفضل مقطع الفيديو الخاص بك!" });
                return;
            }
        } else {
            await msg.reply(responseText);
        }

    } catch (error: any) {
        console.error("WhatsApp Error:", error);
        await msg.reply(`❌ حدث خطأ: ${error.message}`);
    }
});

client.initialize();
